### ISSUE TITLE
Making a complied version in Ruby 1.9.2 or 2.2

### ISSUE THREAD

**Issue by ghost** [edwinacunav/hiddenchest#1]
redacted

**Comment by ghost** [comment]
So, I was going through most of what was going on endlessly researching.
Is there anyway I can compile the program into 1.9.2 ruby instead of 2.6.
It breaks my game and I really don't want to reprogram the entirety of the game to do so.

**Comment by edwinacunav** [comment]
Let me take a look at some of your code. Normally there are just few things that need to be changed.

The usual suspects are:

- non initialized local variables
- case variable
when value : result
end
- A hash defined taking advantage of a bug that let you define a group of values in an incorrect way

The rest of your code should be safe as far as I've seen in my own game projects. Plus you've got a lot of convenient methods in Ruby 2.6 like 100.clamp(0, 50) #=> 50 making it unnecessary to call an Array's min and max methods and it's a fast solution.

Plus an old version I've compiled for Windows included a bug that ignored animations but it has been fixed since version 1.48 or so.

**Comment by ghost** [comment]
The version my game uses is this build - https://github.com/Daverball/mkxp/tree/lisa

I don't know much about Ruby, still am learning.
Once I get home I will send you a video of what happens of to the game when it is used in the HiddenChest engine.
I have asked a friend to compile a hybrid of MKXP-LISA to have many features that will overall fix my concerns about the game.
The only thing I wanted out of HiddenChest was the Widescreen support which I found to be awesome.
My game just doesn't work in HiddenChest.

**Comment by edwinacunav** [comment]
The video is not a problem but code examples or a minimal project where you can show me what usually happens on your game is preferred. It makes it easier to deal with any Ruby or C++ coding issues that might show up.

Sadly, your last comment disappointed me a little bit since HiddenChest offers more features than widescreen support. It includes full keyboard support for instance...

What version of RGSS are you using? O_O I don't think you've mentioned it so far...

Anyway, if you don't feel comfortable with sharing the example code or test project, you might keep using your current engine. I don't mind.

**Comment by ghost** [comment]
(sorry for the wait)
The RGSS I am using is VX Ace.
I actually sent you a friend request on Discord so hopefully we can communicate a bit better.
I can share you the code snippets privately since this convo is public.
I also am very interested in HiddenChest just not very skilled at coding.
